Add pygraphviz for redun viz (#215)
Fixes #199

While this PR addresses the missing Python dependency, there may be an underlying issue with the visualization graph. I saw errors like this:

login-1> redun viz --format png --output ~/Downloads/redun-playpen-viz 21927dea
Traceback (most recent call last):
  File "/nix/store/bwwn2559b7jv1p9q8s6791a8cphywwlw-python3-3.12.10-env/lib/python3.12/site-packages/pygraphviz/agraph.py", line 1857, in __new__
    nh = gv.agnode(graph.handle, n.encode(graph.encoding), _Action.find)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/bwwn2559b7jv1p9q8s6791a8cphywwlw-python3-3.12.10-env/lib/python3.12/site-packages/pygraphviz/graphviz.py", line 97, in agnode
    return _graphviz.agnode(g, name, createflag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'agnode: no key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/bwwn2559b7jv1p9q8s6791a8cphywwlw-python3-3.12.10-env/lib/python3.12/site-packages/pygraphviz/agraph.py", line 498, in add_edge
    uh = Node(self, u).handle
         ^^^^^^^^^^^^^
  File "/nix/store/bwwn2559b7jv1p9q8s6791a8cphywwlw-python3-3.12.10-env/lib/python3.12/site-packages/pygraphviz/agraph.py", line 1859, in __new__
    raise KeyError(f"Node {n} not in graph.")
KeyError: "Node (Value(hash='d6b9dd45', value=<redun_psij.job_attributes.JobContext object at 0x7fe72e14a0f0>), 'f554890dcf78f869893459fa736085a13796d4da') not in graph."

Co-authored-by: Simon Guest <simon.guest@agresearch.co.nz>